### ISSUE TITLE
Fail to read from ring-buffer at sequence '1120738'

### ISSUE THREAD

**Issue by bugbugmaker** [camunda-community-hub/zeebe-hazelcast-exporter#140]
Failure message:

```
Fail to read from ring-buffer at sequence '1120738'. The sequence is reported as stale. Continue with new head sequence at '1120752' com.hazelcast.ringbuffer.StaleSequenceException: sequence:1120738 is too small and data store is disabled. The current headSequence is:1120752 tailSequence is:1120765
```

**Comment by saig0** [comment]
@bugbugmaker the provided failure message is expected. It indicates that Zeebe exports the records faster to the ring-buffer as they are read (e.g. by the simple monitor).

What is your concrete question?

**Comment by bugbugmaker** [comment]
> 

When Zeebe processes are submitted concurrently, 15 processes are submitted, but Zeebe simple monitor only records seven process records, but 15 processes are successful. The background log consistently prints this warning log. What's the problem?

**Comment by saig0** [comment]
You see this warning because the simple monitor doesn't import the records fast enough. You could [increase the capacity](https://github.com/camunda-community-hub/zeebe-hazelcast-exporter#configuration) of the buffer to mitigate the problem.

However, the Hazelcast exporter is not designed to export/import a big amount of data (i.e. not for production usage).
